//
//  suggestions.swift
//  TriviYeah!
//
//  Created by Colby Cook on 4/25/24.
//

import Foundation


let even_odd = ["Even", "Odd"]

let presidents = ["George Washington", "John Adams", "Thomas Jefferson", "James Madison", "James Monroe", "John Quincy Adams", "Andrew Jackson", "Martin Van Buren", "William Henry Harrison", "John Tyler", "James K. Polk", "Zachary Taylor", "Millard Fillmore", "Franklin Pierce", "James Buchanan", "Abraham Lincoln", "Andrew Johnson", "Ulysses S. Grant", "Rutherford B. Hayes", "James A. Garfield", "Chester A. Arthur", "Grover Cleveland", "Benjamin Harrison", "Grover Cleveland", "William McKinley", "Theodore Roosevelt", "William Howard Taft", "Woodrow Wilson", "Warren G. Harding", "Calvin Coolidge", "Herbert Hoover", "Franklin D. Roosevelt", "Harry S. Truman", "Dwight D. Eisenhower", "John F. Kennedy", "Lyndon B. Johnson", "Richard Nixon", "Gerald Ford", "Jimmy Carter", "Ronald Reagan", "George H. W. Bush", "Bill Clinton", "George W. Bush", "Barack Obama", "Donald Trump", "Joe Biden"]

let adamSandlerMovies = [
    "Billy Madison", "Happy Gilmore", "The Wedding Singer", "The Waterboy", "Big Daddy", "Little Nicky", "Mr. Deeds","Punch-Drunk Love","Anger Management","50 First Dates","Spanglish","The Longest Yard","Click","Reign Over Me","I Now Pronounce You Chuck & Larry","You Don't Mess with the Zohan","Bedtime Stories","Funny People","Grown Ups","Just Go with It","Jack and Jill","That's My Boy","Hotel Transylvania","Grown Ups 2","Blended","The Cobbler","Hotel Transylvania 2","Pixels","The Ridiculous 6","Hotel Transylvania 3: Summer Vacation","Murder Mystery","Uncut Gems","Hubie Halloween"
]

let states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

let continents = ["Africa", "Antarctica", "Asia", "Europe", "North America", "Australia", "South America"]

let adultCartoons = ["The Simpsons", "Family Guy", "South Park", "Rick and Morty", "Archer", "Bob's Burgers", "Futurama", "American Dad!", "BoJack Horseman", "Big Mouth", "King of the Hill", "The Boondocks", "Beavis and Butt-Head", "Venture Bros.", "Metalocalypse", "Robot Chicken", "The Cleveland Show", "Aqua Teen Hunger Force", "Daria", "Drawn Together", "The Critic", "F is for Family", "Duckman", "The Ren & Stimpy Show", "Home Movies", "Space Ghost Coast to Coast", "Superjail!", "Mike Tyson Mysteries", "Ugly Americans", "Harvey Birdman, Attorney at Law", "The Oblongs", "The Brak Show", "Clone High", "Moral Orel", "Lucas Bros. Moving Co.", "Xavier: Renegade Angel", "Sealab 2021", "Mission Hill", "Big City Greens", "Squidbillies", "The Venture Bros.", "The Life & Times of Tim", "Brickleberry", "Drawn Together", "The Maxx", "Dilbert", "Hercules: The Animated Series", "Tripping the Rift", "Celebrity Deathmatch", "Stripperella"]

let snackFoodCompanies = ["Cheez-It", "Doritos", "Lay's", "Pringles", "Cheetos", "Ruffles", "Tostitos", "Fritos", "Pop-Tarts", "Ritz", "Oreo", "Chips Ahoy!", "Triscuit", "Wheat Thins", "Cheerios", "Doritos", "Reese's", "Skittles", "M&M's", "Kit Kat", "Twix", "Snickers", "Milky Way", "Hershey's", "Nutella", "Nestle", "Cadbury", "Ferrero Rocher", "Popcorners", "Kettle Brand", "Popchips", "Snyder's of Hanover", "Pretzel Crisps", "Pepperidge Farm", "Annie's", "Clif Bar", "Nature Valley", "Quaker Oats", "Kellogg's", "General Mills", "Nabisco", "Jelly Belly", "Mike and Ike", "Pringles", "Frito-Lay", "Hostess", "Entenmann's", "Ghirardelli", "Russell Stover", "Lindt", "Gummy Bears", "Planters"]

let harryPotterCharacters = ["Harry Potter", "Hermione Granger", "Ron Weasley", "Albus Dumbledore", "Severus Snape", "Rubeus Hagrid", "Sirius Black", "Remus Lupin", "Ginny Weasley", "Fred Weasley", "George Weasley", "Neville Longbottom", "Luna Lovegood", "Draco Malfoy", "Voldemort", "Bellatrix Lestrange", "Lucius Malfoy", "Dobby", "Minerva McGonagall", "Arthur Weasley", "Molly Weasley", "Dolores Umbridge", "Cedric Diggory", "Cho Chang", "Fleur Delacour", "Viktor Krum", "Gilderoy Lockhart", "Professor Trelawney", "Sybill Trelawney", "Horace Slughorn", "Kreacher", "Nagini", "Grawp", "Cornelius Fudge", "Barty Crouch Jr.", "Peter Pettigrew", "Argus Filch", "Filius Flitwick", "Peeves", "Nearly Headless Nick", "Moaning Myrtle", "Mad-Eye Moody", "Bill Weasley", "Charlie Weasley", "Nymphadora Tonks", "Kingsley Shacklebolt", "Regulus Black", "James Potter", "Lily Potter"]


let nflQuarterbacks = ["Tom Brady", "Peyton Manning", "Brett Favre", "Joe Montana", "John Elway", "Dan Marino", "Drew Brees", "Aaron Rodgers", "Steve Young", "Troy Aikman", "Terry Bradshaw", "Ben Roethlisberger", "Roger Staubach", "Kurt Warner", "Jim Kelly", "Fran Tarkenton", "Philip Rivers", "Drew Bledsoe", "Eli Manning", "Warren Moon", "Donovan McNabb", "Jim McMahon", "Boomer Esiason", "Joe Namath", "Randall Cunningham", "Ken Stabler", "Matt Ryan", "Cam Newton", "Russell Wilson", "Andrew Luck", "Matthew Stafford", "Tony Romo", "Dan Fouts", "Philip Rivers", "Michael Vick", "Carson Palmer", "Steve McNair", "Jim Everett", "Jeff Garcia", "Daunte Culpepper", "Rich Gannon", "Jake Plummer", "Doug Flutie", "John Lynch", "Steve Beuerlein", "Bernie Kosar", "Chad Pennington", "Alex Smith", "Derek Carr", "Patrick Mahomes"]

let crimeMovies = ["The Godfather", "Pulp Fiction", "The Shawshank Redemption", "Goodfellas", "Heat", "The Departed", "Scarface", "Reservoir Dogs", "No Country for Old Men", "The Godfather: Part II", "Taxi Driver", "Casino", "City of God", "The Usual Suspects", "American Gangster", "A Clockwork Orange", "Memento", "Fargo", "The Silence of the Lambs", "Drive", "L.A. Confidential", "Training Day", "Se7en", "True Romance", "The French Connection", "The Departed", "Ocean's Eleven", "Eastern Promises", "Gone Girl", "The Town", "Zodiac", "The Untouchables", "American Psycho", "Catch Me If You Can", "Prisoners", "Collateral", "The Killing", "Infernal Affairs", "Bonnie and Clyde", "Heat", "The Irishman", "The Big Lebowski", "The Bone Collector", "The Girl with the Dragon Tattoo", "Kiss Kiss Bang Bang", "The Drop", "The Place Beyond the Pines", "Road to Perdition"]
